import{Movies} from './Movies';
export const MOVIES: Movies[] = [
       {id: 1,nome:'Star Wars I - A Ameaça Fantasma',descricao:'Quando a maquiavélica Federação Comercial planeja invadir o pacífico planeta Naboo, o guerreiro Jedi Qui-Gon Jinn (Liam Neeson) e seu aprendiz Obi-Wan Kenobi (Ewan McGregor) embarcam em uma aventura para tentar salvar o planeta. Viajam com eles a jovem Rainha Amidala (Natalie Portman), que é visada pela Federação pois querem forçá-la a assinar um tratado que é para eles muito importante. Eles têm de viajar para os distantes planetas Tatooine e Coruscant em uma desesperada tentativa de salvar o mundo de Darth Sidious (Ian McDiarmid), o demoníaco líder da Federação que sempre surge em imagens tridimensionais (a ameaça fantasma). Durante a viagem Qui-Gon Jinn conhece um garoto de nove anos que deseja treiná-lo para ser tornar um Jedi, pois o menino tem todas as qualidades para isto. Mas o tempo revelará que nem sempre as coisas são o que aparentam.',foto:'../assets/foto1.jpg'},
       {id: 2,nome:'Star Wars II - A Guerra dos Clones',descricao:'Dez anos após a tentativa frustrada de invasão do planeta Naboo, Obi-Wan Kenobi (Ewan McGregor), Anakin Skywalker (Hayden Christensen) e Padmé Amidala (Natalie Portman) estão juntos novamente. Neste período de tempo Obi-Wan passou de aprendiz a professor dos ensinamentos jedi para Anakin, sendo que ambos foram destacados para proteger a agora senadora Amidala, que tem sua vida ameaçada por facções separatistas da República, que ameaçam desencadear uma guerra civil intergalática. Com o passar do tempo surge um romance proibido entre Anakin e Amidala, pois os cavaleiros jedi não têm permissão para se apaixonarem.',foto:'../assets/foto2.jpg'},
       {id: 3,nome:'Star Wars III - A Vigança dos Sith ',descricao:'As Guerras Clônicas estão em pleno andamento e as diferenças entre o Conselho Jedi e o Chanceler Palpatine (Ian McDiarmid) aumentam cada vez mais. Anakin Skywalker (Hayden Christensen) mantém um elo de lealdade com Palpatine, ao mesmo tempo em que luta para que seu casamento com Padmé Amidala (Natalie Portman) não seja afetado por esta situação. Seduzido por promessas de poder, Anakin se aproxima cada vez mais de Darth Sidious (Ian McDiarmid) até se tornar o temível Darth Vader. Juntos eles tramam um plano para aniquilar de uma vez por todas com os cavaleiros jedi.',foto:'../assets/foto3.jpg'},
       {id: 4,nome:'Star Wars IV - Uma Nova Esperança',descricao:'Luke Skywalker (Mark Hammil) sonha ir para a Academia como seus amigos, mas se vê envolvido em uma guerra intergalática quando seu tio compra dois robôs e com eles encontra uma mensagem da princesa Leia Organa (Carrie Fisher) para o jedi Obi-Wan Kenobi (Alec Guiness) sobre os planos da construção da Estrela da Morte, uma gigantesca estação espacial com capacidade para destruir um planeta. Luke então se junta aos cavaleiros jedi e a Hans Solo (Harrison Ford), um mercenário, e junto com membros da resistência tentam destruir esta terrível ameaça.',foto:'../assets/foto4.jpg'},
       {id: 5,nome:'Star Wars V - O Império Contra-Ataca',descricao:'As forças imperais comandadas por Darth Vader (David Prowse) lançam um ataque contra os membros da resistência, que são obrigados a fugir. Enquanto isso Luke Skywalker (Mark Hamill) tenta encontrar o Mestre Yoda, que poderá ensiná-lo a dominar a “Força” e torná-lo um cavaleiro jedi. No entanto, Darth Vader planeja levá-lo para o lado negro da “Força”.',foto:'../assets/foto5.jpg'},
       {id: 6,nome:'Star Wars VI - O Retorno do Jedi',descricao:'O imperador (Ian McDiarmid) está supervisionando a construção de uma nova Estrela da Morte. Enquanto isso Luke Skywalker (Mark Hamill) liberta Hans Solo (Harrison Ford) e a Princesa Leia (Carrie Fisher) das mãos de Jaba, o pior bandido das galáxias. Luke só se tornará um cavaleiro jedi quando destruir Darth Vader, que ainda pretende atraí-lo para o lado negro da “Força”. No entanto a luta entre os dois vai revelar um inesperado segredo.',foto:'../assets/foto6.jpg'},
       {id: 7,nome:'Star Wars VII - O Despertar da Força',descricao:' Muito tempo após os fatos de “O Retorno de Jedi”, encontra-se a Primeira Ordem, uma organização sombria iniciada após a queda de Darth Vader e do Império. O grupo está em busca do poderoso Jedi Luke Skywalker, mas terão que enfrentar outro grupo em busca de Luke: a Resistência, liderada por Leia.',foto:'../assets/foto7.jpg'}

];
